# Generated by Django 3.0.2 on 2020-10-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscibers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(default='Home', max_length=200)),
            ],
        ),
    ]
