# Generated by Django 3.0.2 on 2020-10-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userscustom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usersCustom',
        ),
    ]
