# Generated by Django 3.0.2 on 2020-09-30 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200815_1613'),
        ('checkout', '0006_user_address_detail_addresstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder_book',
            name='placedorder_book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_who_buy_book', to='home.books'),
        ),
    ]
