# Generated by Django 3.0.2 on 2020-10-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_wishlist'),
        ('checkout', '0007_auto_20200930_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder_book',
            name='coupon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books_which_user_buy', to='cart.cart'),
        ),
    ]
