# Generated by Django 3.0.2 on 2020-10-08 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0008_auto_20201008_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder_book',
            name='coupon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books_which_user_buy', to=settings.AUTH_USER_MODEL),
        ),
    ]
