# Generated by Django 3.0.2 on 2020-10-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200815_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='InStock',
            field=models.BooleanField(default=True),
        ),
    ]
